# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reqlog < Formula
  desc "Search, trace, and stream logs across files, Docker containers, and remote hosts"
  homepage "https://github.com/sagarmaheshwary/reqlog"
  version "0.9.1-rc2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SagarMaheshwary/reqlog/releases/download/v0.9.1-rc2/reqlog_0.9.1-rc2_darwin_amd64.tar.gz"
      sha256 "5bddfc688787078eb8e97c06c22a2ffc06e1d068bc3faa8ea3e83bd2b46fdaf4"

      define_method(:install) do
        bin.install "reqlog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SagarMaheshwary/reqlog/releases/download/v0.9.1-rc2/reqlog_0.9.1-rc2_darwin_arm64.tar.gz"
      sha256 "1a370456e56959de1ad3a82785703823f360ae21829d95e86ffe9c7f06322ba6"

      define_method(:install) do
        bin.install "reqlog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SagarMaheshwary/reqlog/releases/download/v0.9.1-rc2/reqlog_0.9.1-rc2_linux_amd64.tar.gz"
      sha256 "16328cffb4d5d2450e3825126bf143a7f67a545cce26d9e0d6e714fbb17e7da8"
      define_method(:install) do
        bin.install "reqlog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SagarMaheshwary/reqlog/releases/download/v0.9.1-rc2/reqlog_0.9.1-rc2_linux_arm64.tar.gz"
      sha256 "8ddeec87785be31b185cb748663699e2d60e083fce4728eb6197a450c8c9a134"
      define_method(:install) do
        bin.install "reqlog"
      end
    end
  end

  test do
    system "#{bin}/reqlog", "--version"
  end
end
