# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reqlog < Formula
  desc "Search and trace logs across files, Docker containers and remote hosts"
  homepage "https://github.com/sagarmaheshwary/reqlog"
  version "0.9.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SagarMaheshwary/reqlog-test/releases/download/v0.9.6/reqlog_0.9.6_darwin_amd64.tar.gz"
      sha256 "12114039487e29ec079c2e7488a4f233d848b7a556eabc031fa53b17ee7f4b67"

      define_method(:install) do
        bin.install "reqlog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SagarMaheshwary/reqlog-test/releases/download/v0.9.6/reqlog_0.9.6_darwin_arm64.tar.gz"
      sha256 "c6688b30d4d46df2c8dd8586bd6911eda70e395b68d0e51e86dd946863705817"

      define_method(:install) do
        bin.install "reqlog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SagarMaheshwary/reqlog-test/releases/download/v0.9.6/reqlog_0.9.6_linux_amd64.tar.gz"
      sha256 "5463cf02f653165f05739c0818d4f6a9ecadab2d61f7fa65a041b91c6d3835bd"
      define_method(:install) do
        bin.install "reqlog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SagarMaheshwary/reqlog-test/releases/download/v0.9.6/reqlog_0.9.6_linux_arm64.tar.gz"
      sha256 "8f69bd8c0ec3ea9bb47c5b591e008bc24b476305c5909bb0ad203d009e7b4d86"
      define_method(:install) do
        bin.install "reqlog"
      end
    end
  end

  test do
    system "#{bin}/reqlog", "--version"
  end
end
